project:
  type: website

website:
  title: "Janneke van der Zwaan"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jvdzwaan
      - icon: twitter
        href: https://twitter.com/jvdzwa
format:
  html:
    theme: flatly
    css: styles.css
